[package]
name = "reddit_scraper"
version = "0.1.0"
authors = ["Kirill Voloshin <voloshin.k@husky.neu.edu>"]

[dependencies]
rawr = "0.1.1"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4"
regex = "1.0"
structopt = "0.2.12"
